name: Backend CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - '**'  # 모든 브랜치 PR에도 실행  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker Image Tag
        id: set_tag
        run: |
          if [ "${{ github.ref_name }}" == "develop" ]; then
            DOCKER_IMAGE_TAG="release-${GITHUB_SHA::7}"
          else
            DOCKER_IMAGE_TAG="pr-${{ github.event.pull_request.number }}-${{ github.run_number }}"
          fi
          echo "Docker Image Tag: $DOCKER_IMAGE_TAG"
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        env:
          DOCKER_IMAGE_TAG: ${{ steps.set_tag.outputs.DOCKER_IMAGE_TAG }}
        run: |
          # 가변 태그
          docker build -t hwnahee/backend:$DOCKER_IMAGE_TAG .
          # develop 브랜치 푸시인 경우 고정 태그도 추가
          if [ "${{ github.ref_name }}" = "develop" ]; then
            docker tag hwnahee/backend:$DOCKER_IMAGE_TAG hwnahee/backend:develop
            docker push hwnahee/backend:develop
          fi
          # 공통으로 가변 태그 push
          docker push hwnahee/backend:$DOCKER_IMAGE_TAG

      - name: Trigger CD repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_FOR_DISPATCH }}
          repository: 2025-Techeer-Summer-Bootcamp-Team-C/deploy
          event-type: deploy-backend
          client-payload: |
            { "image_tag": "${{ steps.set_tag.outputs.DOCKER_IMAGE_TAG }}" }
